// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.

// Generated by Quartus Prime Version 22.1std.2 Build 922 07/20/2023 SC Lite Edition
// Created on Wed Dec  3 21:08:45 2025

// synthesis message_off 10175

`timescale 1ns/1ns

module counter3Beven (
    reset,clock,
    C,B,A);

    input reset;
    input clock;
    tri0 reset;
    output C;
    output B;
    output A;
    reg C;
    reg B;
    reg A;
    reg [3:0] fstate;
    reg [3:0] reg_fstate;
    parameter state2=0,state3=1,state4=2,state1=3;

    always @(posedge clock)
    begin
        if (clock) begin
            fstate <= reg_fstate;
        end
    end

    always @(fstate or reset)
    begin
        if (reset) begin
            reg_fstate <= state1;
            C <= 1'b0;
            B <= 1'b0;
            A <= 1'b0;
        end
        else begin
            C <= 1'b0;
            B <= 1'b0;
            A <= 1'b0;
            case (fstate)
                state2: begin
                    reg_fstate <= state3;

                    A <= 1'b0;

                    B <= 1'b1;

                    C <= 1'b0;
                end
                state3: begin
                    reg_fstate <= state4;

                    A <= 1'b0;

                    B <= 1'b0;

                    C <= 1'b1;
                end
                state4: begin
                    reg_fstate <= state1;

                    A <= 1'b0;

                    B <= 1'b1;

                    C <= 1'b1;
                end
                state1: begin
                    reg_fstate <= state2;

                    A <= 1'b0;

                    B <= 1'b0;

                    C <= 1'b0;
                end
                default: begin
                    C <= 1'bx;
                    B <= 1'bx;
                    A <= 1'bx;
                    $display ("Reach undefined state");
                end
            endcase
        end
    end
endmodule // counter3Beven
