-- Copyright (C) 2023  Intel Corporation. All rights reserved.
-- Your use of Intel Corporation's design tools, logic functions 
-- and other software and tools, and any partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Intel Program License 
-- Subscription Agreement, the Intel Quartus Prime License Agreement,
-- the Intel FPGA IP License Agreement, or other applicable license
-- agreement, including, without limitation, that your use is for
-- the sole purpose of programming logic devices manufactured by
-- Intel and sold by Intel or its authorized distributors.  Please
-- refer to the applicable agreement for further details, at
-- https://fpgasoftware.intel.com/eula.

-- Generated by Quartus Prime Version 22.1std.2 Build 922 07/20/2023 SC Lite Edition
-- Created on Sun Dec  7 19:38:36 2025

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY TrafficLights IS
    PORT (
        reset : IN STD_LOGIC := '0';
        clock : IN STD_LOGIC;
        TL : IN STD_LOGIC := '0';
        TS : IN STD_LOGIC := '0';
        VS : IN STD_LOGIC := '0';
        MG : OUT STD_LOGIC;
        MY : OUT STD_LOGIC;
        MR : OUT STD_LOGIC;
        SG : OUT STD_LOGIC;
        SY : OUT STD_LOGIC;
        SR : OUT STD_LOGIC;
        ST1 : OUT STD_LOGIC;
        ST2 : OUT STD_LOGIC;
        ST3 : OUT STD_LOGIC;
        ST4 : OUT STD_LOGIC
    );
END TrafficLights;

ARCHITECTURE BEHAVIOR OF TrafficLights IS
    TYPE type_fstate IS (state1,state2,state3,state4);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,TL,TS,VS)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= state1;
            MG <= '0';
            MY <= '0';
            MR <= '0';
            SG <= '0';
            SY <= '0';
            SR <= '0';
            ST1 <= '0';
            ST2 <= '0';
            ST3 <= '0';
            ST4 <= '0';
        ELSE
            MG <= '0';
            MY <= '0';
            MR <= '0';
            SG <= '0';
            SY <= '0';
            SR <= '0';
            ST1 <= '0';
            ST2 <= '0';
            ST3 <= '0';
            ST4 <= '0';
            CASE fstate IS
                WHEN state1 =>
                    IF (((TL = '1') OR NOT((VS = '1')))) THEN
                        reg_fstate <= state1;
                    ELSIF ((NOT((TL = '1')) AND (VS = '1'))) THEN
                        reg_fstate <= state2;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= state1;
                    END IF;

                    MG <= '1';

                    SR <= '1';

                    ST1 <= '1';
                WHEN state2 =>
                    IF ((TS = '1')) THEN
                        reg_fstate <= state2;
                    ELSIF (NOT((TS = '1'))) THEN
                        reg_fstate <= state3;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= state2;
                    END IF;

                    ST2 <= '1';

                    MY <= '1';

                    SR <= '1';
                WHEN state3 =>
                    IF (((TL = '1') AND (VS = '1'))) THEN
                        reg_fstate <= state3;
                    ELSIF ((NOT((TL = '1')) OR NOT((VS = '1')))) THEN
                        reg_fstate <= state4;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= state3;
                    END IF;

                    MR <= '1';

                    SG <= '1';

                    ST3 <= '1';
                WHEN state4 =>
                    IF (NOT((TS = '1'))) THEN
                        reg_fstate <= state1;
                    ELSIF ((TS = '1')) THEN
                        reg_fstate <= state4;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= state4;
                    END IF;

                    MR <= '1';

                    SY <= '1';

                    ST4 <= '1';
                WHEN OTHERS => 
                    MG <= 'X';
                    MY <= 'X';
                    MR <= 'X';
                    SG <= 'X';
                    SY <= 'X';
                    SR <= 'X';
                    ST1 <= 'X';
                    ST2 <= 'X';
                    ST3 <= 'X';
                    ST4 <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
